apiVersion: v2
name: gotenberg
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
description: A Helm chart for Gotenberg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.14.0"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "8.25.1"

keywords:
  - gotenberg
  - pdf

sources:
  - https://github.com/gotenberg/gotenberg
  - https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg

maintainers:
  - name: MaikuMori
    email: mikskalnins@maikumori.com
    url: maikumori.com

annotations:
  # This annotation allows including named links, which will be rendered nicely in Artifact Hub.
  # You can use this annotation to include links not included previously in the Chart.yaml file,
  # or you can use it to name links already present (in the sources section, for example).
  artifacthub.io/links: |
    - name: Projects Homepage
      url: https://gotenberg.dev/
    - name: Projects GitHub
      url: https://github.com/gotenberg/gotenberg
    - name: Chart's GitHub
      url: https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg
    - name: Chart's Changelog
      url: https://github.com/MaikuMori/helm-charts/blob/master/charts/gotenberg/CHANGELOG.md
  artifacthub.io/changes: |
    - kind: added
      description: Ability to set labels on ingress resource
      links:
        - name: GitHub PR
          url: https://github.com/MaikuMori/helm-charts/pull/77
        - name: GitHub Contributor
          url: https://github.com/Vovcharaa
    - kind: added
      description: Changelog annotations to Chart.yaml for Artifact Hub
      links:
        - name: GitHub Issue
          url: https://github.com/MaikuMori/helm-charts/issues/65
    - kind: fixed
      description: HOME environment variable conflict when set in extraEnv - user's explicit setting now takes precedence
      links:
        - name: GitHub Issue
          url: https://github.com/MaikuMori/helm-charts/issues/74
